return {
  {
    "nvim-treesitter/nvim-treesitter",
    main = "nvim-treesitter.configs",
    event = { "BufReadPost", "BufNewFile" },
    build = ":TSUpdate",
    opts = {
      highlight = {
        enable = true,
        disable = function(_, bufnr) return vim.api.nvim_buf_line_count(bufnr) > 10000 end,
      },
      incremental_selection = { enable = true },
      indent = { enable = true },
      context_commentstring = {
        enable = true,
        enable_autocmd = false,
      },
      ensure_installed = {
        "bash",
        "c",
        "lua",
        "html",
        "css",
        "javascript",
        "jsdoc",
        "json",
        "toml",
        "luadoc",
        "luap",
        "markdown",
        "markdown_inline",
        "python",
        "rust",
        "tsx",
        "typescript",
        "vim",
        "yaml",
        "sql",
        "query",
        "java",
        "kotlin",
        "http",
        "ebnf",
        "dot",
        "fish",
        "kdl",
      },
    },
  },

  {
    "windwp/nvim-ts-autotag",
    ft = {
      "astro",
      "html",
      "markdown",
      "php",
      "javascriptreact",
      "typescriptreact",
      "xml",
    },
    opts = {},
  },
}
