return {
  "gorbit99/codewindow.nvim",
  event = { "BufReadPost", "BufNewFile" },
  opts = {
    auto_enable = true,
    exclude_filetypes = {
      "help",
      "startify",
      "aerial",
      "alpha",
      "dashboard",
      "lazy",
      "neogitstatus",
      "neo-tree",
      "Trouble",
      "noice",
      "qf",
      "mason",
      "oil",
      "",
    },
    relative = "editor",
    width_multiplier = 3,
    window_border = "",
  },
}
